import Header from '@/components/Header'
import './globals.css'

export const metadata = {
  title: 'IMDB App',
  description: 'Generated by ersin'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {/* Header */}
        <Header />
        {/* Navbar */}
        {/* SearchBox */}
        {children}
      </body>
    </html>
  )
}
